using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Shared.Models;
using Shared.Api;

namespace Client.Core.Api;

[JsonSourceGenerationOptions(
  PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(EnrollRequest))]
[JsonSerializable(typeof(EnrollResponse))]
[JsonSerializable(typeof(CameraDto))]
[JsonSerializable(typeof(IReadOnlyList<CameraDto>))]
[JsonSerializable(typeof(List<CameraDto>))]
[JsonSerializable(typeof(CreateCameraRequest))]
[JsonSerializable(typeof(UpdateCameraRequest))]
[JsonSerializable(typeof(ProbeRequest))]
[JsonSerializable(typeof(ProbeResponse))]
[JsonSerializable(typeof(ClientDto))]
[JsonSerializable(typeof(IReadOnlyList<ClientDto>))]
[JsonSerializable(typeof(List<ClientDto>))]
[JsonSerializable(typeof(UpdateClientRequest))]
[JsonSerializable(typeof(StartEnrollmentResponse))]
[JsonSerializable(typeof(DiscoveryRequest))]
[JsonSerializable(typeof(DiscoveredCameraDto))]
[JsonSerializable(typeof(IReadOnlyList<DiscoveredCameraDto>))]
[JsonSerializable(typeof(List<DiscoveredCameraDto>))]
[JsonSerializable(typeof(RecordingSegmentDto))]
[JsonSerializable(typeof(IReadOnlyList<RecordingSegmentDto>))]
[JsonSerializable(typeof(List<RecordingSegmentDto>))]
[JsonSerializable(typeof(TimelineResponse))]
[JsonSerializable(typeof(EventDto))]
[JsonSerializable(typeof(IReadOnlyList<EventDto>))]
[JsonSerializable(typeof(List<EventDto>))]
[JsonSerializable(typeof(RetentionPolicy))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(StorageResponse))]
[JsonSerializable(typeof(ServerSettings))]
[JsonSerializable(typeof(PluginDto))]
[JsonSerializable(typeof(IReadOnlyList<PluginDto>))]
[JsonSerializable(typeof(List<PluginDto>))]
[JsonSerializable(typeof(SettingGroup))]
[JsonSerializable(typeof(IReadOnlyList<SettingGroup>))]
[JsonSerializable(typeof(List<SettingGroup>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(ValidateFieldRequest))]
[JsonSerializable(typeof(CredentialsDto))]
[JsonSerializable(typeof(StreamProfileDto))]
[JsonSerializable(typeof(StorageStoreDto))]
[JsonSerializable(typeof(StorageBreakdownDto))]
[JsonSerializable(typeof(TimelineSpanDto))]
[JsonSerializable(typeof(TimelineEventDto))]
[JsonSerializable(typeof(SettingField))]
[JsonSerializable(typeof(SettingFieldOption))]
[JsonSerializable(typeof(IReadOnlyList<SettingFieldOption>))]
[JsonSerializable(typeof(ResponseEnvelope))]
[ExcludeFromCodeCoverage]
internal partial class ClientJsonContext : JsonSerializerContext;
