using System.Text.Json;
using System.Text.Json.Serialization;
using Shared.Models;
using Shared.Models.Dto;

namespace Server.Core;

[JsonSourceGenerationOptions(
  PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ResponseEnvelope))]
[JsonSerializable(typeof(EnrollRequest))]
[JsonSerializable(typeof(EnrollResponse))]
[JsonSerializable(typeof(StartEnrollmentResponse))]
[JsonSerializable(typeof(CameraListItem))]
[JsonSerializable(typeof(IReadOnlyList<CameraListItem>))]
[JsonSerializable(typeof(List<CameraListItem>))]
[JsonSerializable(typeof(CreateCameraRequest))]
[JsonSerializable(typeof(UpdateCameraRequest))]
[JsonSerializable(typeof(ProbeRequest))]
[JsonSerializable(typeof(ProbeResponse))]
[JsonSerializable(typeof(ClientListItem))]
[JsonSerializable(typeof(IReadOnlyList<ClientListItem>))]
[JsonSerializable(typeof(List<ClientListItem>))]
[JsonSerializable(typeof(UpdateClientRequest))]
[JsonSerializable(typeof(DiscoveryRequest))]
[JsonSerializable(typeof(DiscoveredCameraDto))]
[JsonSerializable(typeof(IReadOnlyList<DiscoveredCameraDto>))]
[JsonSerializable(typeof(List<DiscoveredCameraDto>))]
[JsonSerializable(typeof(RecordingSegmentDto))]
[JsonSerializable(typeof(IReadOnlyList<RecordingSegmentDto>))]
[JsonSerializable(typeof(List<RecordingSegmentDto>))]
[JsonSerializable(typeof(TimelineResponse))]
[JsonSerializable(typeof(TimelineSpan))]
[JsonSerializable(typeof(TimelineEvent))]
[JsonSerializable(typeof(EventDto))]
[JsonSerializable(typeof(IReadOnlyList<EventDto>))]
[JsonSerializable(typeof(List<EventDto>))]
[JsonSerializable(typeof(RetentionPolicy))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(VerifyRemoteAddressResponse))]
[JsonSerializable(typeof(StorageResponse))]
[JsonSerializable(typeof(StorageStoreDto))]
[JsonSerializable(typeof(StorageBreakdownItem))]
[JsonSerializable(typeof(ServerSettings))]
[JsonSerializable(typeof(PortForwardingStatus))]
[JsonSerializable(typeof(PluginListItem))]
[JsonSerializable(typeof(IReadOnlyList<PluginListItem>))]
[JsonSerializable(typeof(List<PluginListItem>))]
[JsonSerializable(typeof(SettingGroup))]
[JsonSerializable(typeof(IReadOnlyList<SettingGroup>))]
[JsonSerializable(typeof(List<SettingGroup>))]
[JsonSerializable(typeof(SettingField))]
[JsonSerializable(typeof(SettingFieldOption))]
[JsonSerializable(typeof(IReadOnlyList<SettingFieldOption>))]
[JsonSerializable(typeof(ValidateFieldRequest))]
[JsonSerializable(typeof(CredentialsDto))]
[JsonSerializable(typeof(StreamProfileDto))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(CameraConfigSchema))]
[JsonSerializable(typeof(CameraConfigValues))]
[JsonSerializable(typeof(Dictionary<string, IReadOnlyList<SettingGroup>>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, IReadOnlyList<SettingGroup>>>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, string>>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, Dictionary<string, string>>>))]
public partial class ServerJsonContext : JsonSerializerContext;
