using System.Text.Json;
using System.Text.Json.Serialization;
using Shared.Models;
using Shared.Api;

namespace Server.Core;

[JsonSourceGenerationOptions(
  PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ResponseEnvelope))]
[JsonSerializable(typeof(EnrollRequest))]
[JsonSerializable(typeof(EnrollResponse))]
[JsonSerializable(typeof(StartEnrollmentResponse))]
[JsonSerializable(typeof(CameraDto))]
[JsonSerializable(typeof(IReadOnlyList<CameraDto>))]
[JsonSerializable(typeof(List<CameraDto>))]
[JsonSerializable(typeof(CreateCameraRequest))]
[JsonSerializable(typeof(UpdateCameraRequest))]
[JsonSerializable(typeof(ProbeRequest))]
[JsonSerializable(typeof(ProbeResponse))]
[JsonSerializable(typeof(ClientDto))]
[JsonSerializable(typeof(IReadOnlyList<ClientDto>))]
[JsonSerializable(typeof(List<ClientDto>))]
[JsonSerializable(typeof(UpdateClientRequest))]
[JsonSerializable(typeof(DiscoveryRequest))]
[JsonSerializable(typeof(DiscoveredCameraDto))]
[JsonSerializable(typeof(IReadOnlyList<DiscoveredCameraDto>))]
[JsonSerializable(typeof(List<DiscoveredCameraDto>))]
[JsonSerializable(typeof(RecordingSegmentDto))]
[JsonSerializable(typeof(IReadOnlyList<RecordingSegmentDto>))]
[JsonSerializable(typeof(List<RecordingSegmentDto>))]
[JsonSerializable(typeof(TimelineResponse))]
[JsonSerializable(typeof(TimelineSpanDto))]
[JsonSerializable(typeof(TimelineEventDto))]
[JsonSerializable(typeof(EventDto))]
[JsonSerializable(typeof(LiveEventDto))]
[JsonSerializable(typeof(IReadOnlyList<EventDto>))]
[JsonSerializable(typeof(List<EventDto>))]
[JsonSerializable(typeof(RetentionPolicy))]
[JsonSerializable(typeof(SystemEventRetentionDto))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(VerifyRemoteAddressResponse))]
[JsonSerializable(typeof(StorageResponse))]
[JsonSerializable(typeof(StorageStoreDto))]
[JsonSerializable(typeof(StorageBreakdownDto))]
[JsonSerializable(typeof(ServerSettings))]
[JsonSerializable(typeof(PortForwardingStatusDto))]
[JsonSerializable(typeof(PluginDto))]
[JsonSerializable(typeof(IReadOnlyList<PluginDto>))]
[JsonSerializable(typeof(List<PluginDto>))]
[JsonSerializable(typeof(SettingGroup))]
[JsonSerializable(typeof(IReadOnlyList<SettingGroup>))]
[JsonSerializable(typeof(List<SettingGroup>))]
[JsonSerializable(typeof(SettingField))]
[JsonSerializable(typeof(SettingFieldOption))]
[JsonSerializable(typeof(IReadOnlyList<SettingFieldOption>))]
[JsonSerializable(typeof(ValidateFieldRequest))]
[JsonSerializable(typeof(CredentialsDto))]
[JsonSerializable(typeof(StreamProfileDto))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(CameraConfigSchemaResponse))]
[JsonSerializable(typeof(CameraConfigValues))]
[JsonSerializable(typeof(Dictionary<string, IReadOnlyList<SettingGroup>>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, IReadOnlyList<SettingGroup>>>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, string>>))]
[JsonSerializable(typeof(Dictionary<string, Dictionary<string, Dictionary<string, string>>>))]
public partial class ServerJsonContext : JsonSerializerContext;
